const translations = {
    cz: {
        home: {
            title: "Minecraft Hosting Zdarma",
            subtitle: "Hostování je naše profese; šťastní zákaznící jsou naší prioritou. Zaměřujeme se na nejlepší kvalitu Minecraft servrů na trhu, s použítí nejnovější technologie.",
            button_register: "Registrace",
            button_dashboard: "Dashboard",
            nav_contact: "Kontakt",
            nav_panel: "Panel",
            nav_dashboard: "Client Area",
            nav_button: "Přihlásit se",
            plans_title: "Naše plány",
            plans_subtitle: "Naše hostované servry minecraft používají úložiště SSD od základů. S MChost si můžete užít zvýšený výkon, dodržování předpisů a plnou kontrolu nad vaším servrem .",
            plan_free_title: "Zdarma",
            plan_premium_title: "Premium",
            plan_bungee_title: "Bungee Balíček",
            plan_custom_title: "Vlastní",
            plan_free_plugins: "Neomezeno Pluginů",
            plan_free_players: "Neomezeno Hráčů",
            plan_free_nolimit: "Žádné slot ani plugin limity",
            plan_free_online: "24/7 online, žádné fronty",
            plan_dedicated_ports: "%s dedikováné porty",
            plan_online: "online",
            plan_custom_ports: "porty",
            plan_free_get: "Příhlásit se",
            plan_premium_get: "Získej Premium",
            plan_bungee_get: "Získej Balíček",
            plan_custom_get: "Získej Custom balíček",
            plan_free_support: "Úžasná Technická Podpora",
            plan_premium_support: "Dedikovaná Technická Podpora",
            plan_bungee_support: "Prioritní Technická Podpora",
            features_title: "Proč je to tak skvělé?",
            features_subtitle: "Protože jsme se odhodlali nabídnout to nejlepší pro vás.",
            features_support_title: "Live support",
            features_support_subtitle: 'Náš tým podpory je živě na našem <a href="%s" class="text-white text-underline" target="_blank">Discord servru</a> aby ti kdykoli pomohl!',
            features_uptime_title: "99% Doba provozu",
            features_uptime_subtitle: 'Ale neberte to za naše slovo. Podívejte se sami <a href="%s" class="text-white text-underline" target="_blank">zde</a>.',
            features_tech_title: "Špičková Technologie",
            features_tech_subtitle: "Neustále upgrajdujeme naše služby, aby vaše servry byli aktuální a co nejrychlejší.",
            features_title2: "Součástí všech plánů",
            features_subtitle2: "These are the core features and characteristics of all Minecraft hosting plans that we offer.",
            features_ddos_title: "DDoS Ochrana",
            features_ddos_subtitle: "We utilise layer 7 reverse proxies to withstand and counter distributed denial of service attacks with ease.",
            features_disk_title: "NVMe SSD",
            features_disk_subtitle: "Čas který potřebuje server na boot zavisí na disku. Proto jsme šli pro to nejlepší.",
            features_scalability_title: "Scalability",
            features_scalability_subtitle: "Náš kontrolní panel tě nechá upgradovat tvůj server pomocí pár kliknutí, kdykoli budeš chtít. Začni s čím budeš potřebovat, a při růstu vaší hráčské základny se přesuň na silnější stroj..",
            features_panel_title: "Pterodactyl Control Panel",
            features_panel_subtitle: "Multi-server managment nebyl nikdy jednoduší s Pterodactyl web panelem a interfacem. Přímý přístup k vaším souborům, servrový terminál a sub-users.",
            features_sftp_title: "SFTP",
            features_sftp_description: "Bezpečnost nikdy nebyla zanedbaná v MChost. Secure File Transfer Protocol který jsme implementovalo umožňuje spravovat data odkudkoli, bezpečně.",
            features_scheduler_title: "Plánovač úkolů",
            features_scheduler_subtitle: "Používáme CRON na to aby jsme ti povolili plánování aktivit na tvém servru, jako je pravidelné restartovaní, nebo jakýkoli další příkaz.",
            about_title: "O nás",
            about_subtitle: "Jsme ctižádostiví a odhodlaní poskytovat nejlepší a nejkvalitnější hosting servrů. Pracujeme dnem i nocí, aby jsme nastavili možně nejlepší nodes, takže si můžeš užívat příjemné a ničím nerušené hraní s kamarády na svém Minecraft servru.",
            reviews_title: "Hodnocení",
            reviews_subtitle: "Nevěříte, že je to tak skvélé. Tady je co o nás říkají naší zákaznící!",
            review1_title: "Nebudu lhát, tenhle hosting je nejlepší",
            review1_text: "Tohle to je nejlepší hosting, který jsem použil. Výkon je taktéž nejlepší, dokonce když váš server nepotřebuje tolik RAM.",
            review2_title: "Je to velmi dobrý hosting",
            review2_text: "Hosting je velmi dobrý! Žádné lagy, žádné TPS pod 19.9. Prostě skvělý!",
            review3_title: "Nejlepší Hostingová Služba!",
            review3_text: "Tohle to je jeden z nejlepších hostingových služeb, se kterou jsem se kdy setkal, a jsem rád, že jsem ji našel. Rozhodně mi to zachránilo pár babek!",
            review4_title: "Úžasné",
            review4_text: "Dají vám přístup do SFTP a web panelu. Není to jako ostaní služby, která vás limitují, co můžete dělat. Je to jako by jste si koupili správný server. Jsem velmi šťastný, že jsem to našel.",
            panel_title: "Featuring Pterodactyl",
            panel_subtitle: "Pterodactyl is the best Minecraft server management panel, designed with security in mind, it runs all servers in isolated Docker containers while exposing a beautiful and intuitive UI.",
            need_support: 'Pořád hledáš informace? <a href="%s">Získej podporu zde,</a> nebo se připoj k nám do naší<a href="%s" target="_blank">Discord comunity</a>.',
            start_title: "Spusť svůj server ještě dnes!",
            start_subtitle: "Na co čekáš? Je to zdarma!",
            support_title: "Live Expert Support",
            support_subtitle: 'Potřebuješ okamžitou asistenci, nebo se chceš jenom zeptat na pár otázek? <a href="https://discord.gg/Wx95Nx3" target="_blank">Připoj se do naší Discord komunity</a> a chatuj s agentem podpory. Také nám můžeš napsat e-mail na <a href="mailto:support@mchost.cc">support@mchost.cc</a> kdykoli budeš potřebovat.',
            footer_information: "Informace",
            footer_pages: "Stránky",
            footer_more: "Více",
            footer_page_terms: "Podmínky použití",
            footer_page_privacy: "Zásady Ochrany Osobních Údajů",
            footer_page_mc: "Minecraft Hosting",
            footer_page_pricing: "Ceny",
            footer_page_order: "Objednat",
            footer_page_blog: "Blog",
            footer_powered: "Powered by",
            footer_copyright: "Všechna Práva Vyhrazena."
        },
        contact: {
            title: "Kontaktujte nás",
            field_name: "Jméno",
            placeholder_name: "Prosím napište svoje jméno",
            field_organisation: "Organizace",
            placeholder_organisation: "Prosím napište jméno své organizace",
            field_email: "Email",
            placeholder_email: "Prosím napište svůj Email",
            field_phone: "Telefon",
            placeholder_phone: "Prosím napište svoje telefonní číslo",
            field_message: "Zpravá",
            placeholder_message: "Zpravá pro nás",
            button_send: "Poslat zprávu",
            note: '* Tato pole jsou povinná. Odesláním souhlasíte s <a href="%s" target="_blank">Podmínkama použití</a>.'
        },
        hosting: {
            title: "Minecraft Hosting",
            subtitle: "2GB RAM zdarma Minecraft Hostingu. 100% NVMe SSD úložiště, 24/7, žádné hloupé fronty, žádné limity hráčů, žádné limity pluginů, jakákoli Minecraft verze kterou máte rádi! Začnětě teď, je to zdarma.",
            plan_traffic: "Neomezený provoz",
            plan_ddos: "Ochrana 7 DDoS vrstev"
        },
        order: {
            title: "Objednávka",
            field_name: "jméno",
            placeholder_name: "Prosím napište svoje jméno",
            field_email: "Email",
            placeholder_email: "Prosím napište svůj email",
            field_pp_email: "PayPal E-mail",
            field_more: "Další Instrukce",
            button: "Vyžádat Objednávku",
            note: '* Tato pole jsou povinná. Odesláním souhlasíte s <a href="%s" target="_blank">Podmínkama použití</a>.'
        },
        support: {
            title: "Podpora",
            subtitle: "Můžete nás zastihnout kdekoli. Tady jsou nějaké možnosti!",
            faq_title: "Často Kladené Otázky",
            faq_text: "Check out our knowledge base before asking a question. There's a chance it has already been answered for you.",
            dc_title: "Discord Live Support",
            dc_text: "Klikni na tlačítko níže, a přidej se do našeho Discord servru a zeptej se na pomoc.",
            email_title: "E-mail",
            email_text: 'Pošli nám email na <a href="mailto:support@mchost.cc">support@mchost.cc</a> a zástupce se s tebou spojí do 12 hodin!',
            form_title: "Kontaktní formulář",
            form_text: "A nebo nám prostě pošli zprávu přes kontaktní formulář."
        },
        arc_earn: {
            title: "Získavání Kreditů",
            subtitle: "Můžeš získávat kredity, které mohou být použity na extra zdroje pomocí otevření stránky. Dostaneš 1 kredit každou hodinu.",
            label: "PROSÍM NAPIŠ JEDNU Z NÁSLEDUJÍCÍCH",
            placeholder: "Discord ID, Klient ID nebo uživatelské jméno panelu",
            get_dc: "Získej ID Discordu",
            get_panel: "Získej své uživatelské jméno",
            get_cid: "Získej své ID Klienta",
            unsure: 'Nejsi si jist jak získat Discord ID, ID Klienta nebo uživatelské jméno? <a href="$s" target="_blank">Kontaktuj nás.',
            keep_open: "Nech tuhle stránku otevřenou, aby jsi získával kredity!",
            earned: 'Získáno touto relací: <b class="credits">%s</b> kreditů',
            btn_quit: "Odejít",
            btn_refresh: "Obnovit",
            btn_blank: "Blank",
            text: 'Nech tuhle stránku otevřenou a budeš dostávat 1 kredit každou hodinu. Když zavřeš stránku, máš 5 minut na to aby jsi ji znovu otevřel před tím než se ti relace resetuje. Jestli chceš získat více kreditů za hodinu, prosím následuj <a href="%s" target="_blank">tenhle tutoriál</a>.',
            video_subtitle: "Můžeš získat kredity, které mohou být použity pro extra zdroje sledováním video reklam.",
            short_title: "Získej kredity zdarma!",
            short_new: 'Otevři tuhle URL <a href="%s">%s</a> aby jsi získal další odměnu',
            short_success: "Úspěšně jsi si vyzvedl svoji odměnu!",
            short_error_title: "Error!",
            short_error_text: "Odměna pro tento hash už byla vyzvednuta, a nebo neexistuje.",
            short_error_new: 'Nevyzvednutá URL speciálně pro tebe: <a href="%s">%s</a>'
        },
        gdpr: {
            text: "Naše webová stránka používá cookies. Prosím přečti si naše Zásady Ochrany Osobních Údajů pro více informací.",
            accept: "Příjmout",
            privacy: "Zásady Ochrany Osobních Údajů"
        },
        dashboard: {
            welcome: "Welcome to your dashboard!",
            btn_panel: "Kontrolní Panel",
            btn_logout: "Odhlásit se",
            servers: "Servry",
            server_create: "Vytvořit server",
            server_name: "Jméno",
            server_actions: "Akce",
            server_unlimited: "Neomezeně",
            balance: "MChost Balance",
            balance_text: "Kredity k dispozici",
            balance_add: "Přidat",
            balance_store: "Obchod",
            balance_send: "Poslat",
            create_title: "Vytvořit server",
            create_name: "Jméno serveru",
            create_quota: "Vaše zbývající kvóta RAM je %s MB",
            create_location: "Lokace",
            create_type: "Typ serveru",
            create_btn: "Vytořeno!",
            btn_close: "Zavřeno",
            panel_title: "Přihlášení do Panelu",
            panel_subtitle: "Toto jsou vaše defaultní přihlašovaní údaje do kontrolního panelu. Prosím uvědomte si, jestli je změníte, zde se nebudou aktualizovat.",
            panel_username: "Uživatelské jméno",
            panel_pass: "Heslo",
            panel_show_pass: "Ukázat Heslo",
            btn_login: "Přihlásit se",
            panel_open: "Otevřít Panel",
            add_title: "Získejte kredity",
            add_buy: "Kupte kredity",
            add_buy_sub: "Top-up your account with credits using PayPal or a debit card.",
            credits: "Kredity",
            add_buy_buy: "Další",
            add_giftcard: "Uplatnit dárkovou kartu",
            add_giftcard_sub: "Uplatněte kód Dárkové Karty od MChost aby jste získali více kreditů!",
            gift_card: "Dárková Karta",
            add_giftcard_btn: "Uplatnit",
            add_idle: "Idling",
            add_idle_sub: "You can earn free credits by keeping our idling page open in your browser.",
            add_idle_btn: "Go idling",
            add_app: "Podívejte se na reklamu <small>(Android)</small>",
            add_app_sub: "Získejte kredity zdarma za sledování reklam v naší mobilní aplikaci.",
            add_app_btn: "Stáhnout",
            add_vid: "Sledujte reklamy <small>(Desktop)</small>",
            add_vid_sub: "Také můžete sledovat reklamy na našem počítačovém prohlížeči, aby jste získali více kreditů.",
            add_vid_btn: "Sledovat",
            add_short: "Zkrácená URL adresa",
            add_short_sub: "Klikněte na tlačítko níže, aby jste získali kredity zdarma.",
            add_short_btn: "Go",
            
        }
    }
}
