const translations = {
    en: {
        home: {
            title: "Free Minecraft Hosting",
            subtitle: "Hosting is our profession; happy customers are the priority. We aim to provide the highest quality Minecraft servers on the market using the latest technologies.",
            button_register: "Register",
            button_dashboard: "Dashboard",
            nav_contact: "Contact",
            nav_panel: "Panel",
            nav_dashboard: "Clients Area",
            nav_button: "Sign Up",
            plans_title: "Our plans",
            plans_subtitle: "Our Minecraft hosting servers are all using SSD storage from the ground up. With MChost you can enjoy increased performance, compliance, and full control over your server.",
            plan_free_title: "Free",
            plan_premium_title: "Premium",
            plan_bungee_title: "Bungee Bundle",
            plan_custom_title: "Custom",
            plan_free_plugins: "Unlimited Plugins",
            plan_free_players: "Unlimited Players",
            plan_free_nolimit: "No slots or plugin limits",
            plan_free_online: "24/7 online, no queues",
            plan_dedicated_ports: "%s dedicated ports",
            plan_online: "online",
            plan_custom_ports: "ports",
            plan_free_get: "Sign Up",
            plan_premium_get: "Get Premium",
            plan_bungee_get: "Get Bundle",
            plan_custom_get: "Get Custom",
            plan_free_support: "Awesome Tech Support",
            plan_premium_support: "Dedicated Tech Support",
            plan_bungee_support: "Priority Tech Support",
            features_title: "Why is it so great?",
            features_subtitle: "Because we have dedicated ourselves to offer the best for you.",
            features_support_title: "Live Support",
            features_support_subtitle: 'Our support team is live on our <a href="%s" class="text-white text-underline" target="_blank">Discord server</a> to assist you anytime!',
            features_uptime_title: "99% Uptime",
            features_uptime_subtitle: 'But don\'t take our word for it. Check out for yourself <a href="%s" class="text-white text-underline" target="_blank">here</a>.',
            features_tech_title: "Leading Edge Technology",
            features_tech_subtitle: "We are constantly upgrading our services so that your servers are up to date and as fast as humanly possible.",
            features_title2: "Included with all plans",
            features_subtitle2: "These are the core features and characteristics of all Minecraft hosting plans that we offer.",
            features_ddos_title: "DDoS Protection",
            features_ddos_subtitle: "We utilise layer 7 reverse proxies to withstand and counter distributed denial of service attacks with ease.",
            features_disk_title: "NVMe SSD",
            features_disk_subtitle: "The time it takes to boot up your server depends directly on the disk. That's why we've gone for the best.",
            features_scalability_title: "Scalability",
            features_scalability_subtitle: "Our control panel lets you upgrade your server with just a few clicks any time you like. Start with what you need and move to more powerful as your player base grows.",
            features_panel_title: "Pterodactyl Control Panel",
            features_panel_subtitle: "Multi-server management has never been easier with the Pterodactyl web panel interface. Directly access your files, the server terminal and sub-users.",
            features_sftp_title: "SFTP",
            features_sftp_description: "Security is never neglected at MChost. The Secure File Transfer Protocol that we have implemented allows you to manage your data from anywhere, securely.",
            features_scheduler_title: "Task Scheduler",
            features_scheduler_subtitle: "We use CRON to allow you to schedule activities on your server such as regular reboots or any other command.",
            about_title: "About us",
            about_subtitle: "We are ambitious and committed to providing the best and highest quality humanly possible hosting servers out there. We worked day and night to set up the best possible nodes so that you can enjoy smooth and pleasant gameplay with your friends on your Minecraft server.",
            reviews_title: "Reviews",
            reviews_subtitle: "Don't take our word for how great it is. Here's what our customers say!",
            review1_title: "Not gonna lie, this hosting is the best",
            review1_text: "This is the best hosting that I have used. The performance is also the greatest, even if your server isn't running with much RAM.",
            review2_title: "It's very good hosting",
            review2_text: "The hosting is very good! No lag, no TPS under 19.9. It's great!",
            review3_title: "Best Hosting Service",
            review3_text: "This is one of the best hosting services I have ever encountered and I'm glad that I found it. It definitely saved me a few bucks!",
            review4_title: "Amazing",
            review4_text: "They give you SFTP and web panel. It's not like other services that greatly limit what you can do. This is as if you bought a proper server. I'm very happy to have found this.",
            panel_title: "Featuring Pterodactyl",
            panel_subtitle: "Pterodactyl is the best Minecraft server management panel, designed with security in mind, it runs all servers in isolated Docker containers while exposing a beautiful and intuitive UI.",
            need_support: 'Still looking for information? <a href="%s">Get support here</a> or join our <a href="%s" target="_blank">Discord community</a>.',
            start_title: "Start your server today!",
            start_subtitle: "What are you waiting for? It's free!",
            support_title: "Live Expert Support",
            support_subtitle: 'Need immediate assistance or just want to ask a couple of questions? <a href="https://discord.gg/Wx95Nx3" target="_blank">Join our Discord community</a> and chat live with a support agent. You can also drop us an e-mail at <a href="mailto:support@mchost.cc">support@mchost.cc</a> anytime you like.',
            footer_information: "Information",
            footer_pages: "Pages",
            footer_more: "More",
            footer_page_terms: "Terms of Use",
            footer_page_privacy: "Privacy Policy",
            footer_page_mc: "Minecraft Hosting",
            footer_page_pricing: "Pricing",
            footer_page_order: "Order",
            footer_page_blog: "Blog",
            footer_powered: "Powered by",
            footer_copyright: "All Rights Reserved."
        },
        contact: {
            title: "Contact us",
            field_name: "Name",
            placeholder_name: "Please enter your name",
            field_organisation: "Organisation",
            placeholder_organisation: "Please enter the name of your Organisation",
            field_email: "Email",
            placeholder_email: "Please enter your email",
            field_phone: "Phone",
            placeholder_phone: "Please enter your phone",
            field_message: "Message",
            placeholder_message: "Message for us",
            button_send: "Send message",
            note: '* These fields are required. By submitting you agree to the <a href="%s" target="_blank">Terms of Use</a>.'
        },
        hosting: {
            title: "Minecraft Hosting",
            subtitle: "2GB RAM free Minecraft Hosting. 100% NVMe SSD storage, 24/7 up, no stupid queues, no player limits, no plugin limits, any Minecraft version you like! Get started now, for free!",
            plan_traffic: "Unlimited traffic",
            plan_ddos: "Layer 7 DDoS Protection"
        },
        order: {
            title: "Order",
            field_name: "Name",
            placeholder_name: "Please enter your name",
            field_email: "Email",
            placeholder_email: "Please enter your email",
            field_pp_email: "PayPal E-mail",
            field_more: "Additional Instructions",
            button: "Request Order",
            note: '* These fields are required. By submitting you agree to the <a href="%s" target="_blank">Terms of Use</a>.'
        },
        support: {
            title: "Support",
            subtitle: "You can reach us anywhere. Here are some options!",
            faq_title: "Frequently Asked Questions",
            faq_text: "Check out our knowledge base before asking a question. There's a chance it has already been answered for you.",
            dc_title: "Discord Live Support",
            dc_text: "Click the button below to join our Discord server and ask for help.",
            email_title: "E-mail",
            email_text: 'E-mail us at <a href="mailto:support@mchost.cc">support@mchost.cc</a> and a representative will get in touch with you within 12 hours!',
            form_title: "Contact form",
            form_text: "Or just send us a message through our contact form."
        },
        arc_earn: {
            title: "Earn Credits",
            subtitle: "You can get credits that can be used for extra resources by idling on a page. You will receive 1 credit every hour.",
            label: "PLEASE ENTER ONE OF THE FOLLOWING",
            placeholder: "Discord ID, Client ID or panel username",
            get_dc: "Get your Discord ID",
            get_panel: "Get your username",
            get_cid: "Get youd Client ID",
            unsure: 'Not sure how to get any of that? <a href="$s" target="_blank">Contact us.',
            keep_open: "Keep this page open to earn credits!",
            earned: 'Earned this session: <b class="credits">0</b> credits',
            btn_quit: "Quit",
            btn_refresh: "Refresh",
            btn_blank: "Blank",
            text: 'Keep this page open and you will receive 1 credit every hour. If you close the page, you have 5 minutes to open it again before your session is reset. If you want to gain more credits per hour, please follow <a href="%s" target="_blank">this tutorial</a>.',
            video_subtitle: "You can get credits that can be used for extra resources by watching rewarded video ads.",
            short_title: "Get a credit for free!",
            short_new: 'Open this URL <a href="%s">%s</a> to get another reward!',
            short_success: "You have successfully claimed your reward!",
            short_error_title: "Error!",
            short_error_text: "The reward for this hash has already been claimed or it does not exist.",
            short_error_new: 'An unclaimed URL specially for you: <a href="%s">%s</a>'
        },
        gdpr: {
            text: "Our website is using cookies. Please read our Privacy Policy to find out more.",
            accept: "Accept",
            privacy: "Privacy Policy"
        },
        dashboard: {
            welcome: "Welcome to your dashboard!",
            btn_panel: "Control Panel",
            btn_logout: "Logout",
            servers: "Servers",
            server_create: "Create server",
            server_name: "Name",
            server_actions: "Actions",
            server_unlimited: "Unlimited",
            balance: "MChost Balance",
            balance_text: "Credits Available",
            balance_add: "Add",
            balance_store: "Store",
            balance_send: "Send",
            create_title: "Create Server",
            create_name: "Server Name",
            create_quota: "Your remaining RAM quota is %s MB",
            create_location: "Location",
            create_type: "Server rype",
            create_btn: "Create!",
            btn_close: "Close",
            panel_title: "Login to Panel",
            panel_subtitle: "These are your default credentials that you can use to log into the control panel. Please note if you change them, they will not update here as well.",
            panel_username: "Username",
            panel_pass: "Password",
            panel_show_pass: "Show password",
            btn_login: "Login",
            panel_open: "Open Panel",
            add_title: "Get Credits",
            add_buy: "Buy credits",
            add_buy_sub: "Top-up your account with credits using PayPal or a debit card.",
            credits: "Credits",
            add_buy_buy: "Next",
            add_giftcard: "Redeem Gift Card",
            add_giftcard_sub: "Redeem a MChost Gift Card code to get more credits!",
            gift_card: "Gift Card",
            add_giftcard_btn: "Redeem",
            add_idle: "Idling",
            add_idle_sub: "You can earn free credits by keeping our idling page open in your browser.",
            add_idle_btn: "Go idling",
            add_app: "Watch an ad <small>(Android)</small>",
            add_app_sub: "Get free credits for watching an advertisement video on our mobile app.",
            add_app_btn: "Download",
            add_vid: "Watch ads <small>(Desktop)</small>",
            add_vid_sub: "You can also watch ads on on your PC browser to earn extra credits.",
            add_vid_btn: "Watch",
            add_short: "Short URLs",
            add_short_sub: "Click the button below to get free credits",
            add_short_btn: "Go",
            
        }
    }
}
