const translations = {
  de: {
    home: {
      title: "Kostenloses Minecraft-Hosting",
      subtitle: "Hosting ist unsere Leidenschaft; glückliche Kunden sind unsere Priorität. Unser Ziel ist es das beste Minecraft-Hosting auf dem Markt, mit den modernsten Technologien anzubieten.", 
      button_register: "Konto erstellen",
      button_dashboard: "Dashboard",
      nav_contact: "Kontakt",
      nav_panel: "Kontrollzentrum",
      nav_dashboard: "Kundenbereich",
      nav_button: "Konto erstellen",
      plans_title: "Unsere Tarife",
      plans_subtitle: "Unsere Minecraft-Server verwenden alle von Grund auf SSD-Speicher. Mit MChost kannst du verbesserte Leistung und volle Kontrolle über deinen Server genießen.",
      plan_free_title: "Kostenlos", 
      plan_premium_title: "Premium",
      plan_bungee_title: "Bungee-Paket",
      plan_custom_title: "Benutzerdefiniert",
      plan_free_plugins: "Unendliche Plugins",
      plan_free_players: "Unendliche Spieler",
      plan_free_nolimit: "Keine Slot oder Plugin beschränkung",
      plan_free_online: "24/7 online, keine Warteschlangen",
      plan_dedicated_ports: "%s dedizierte Ports",
      plan_online: "online",
      plan_custom_ports: "Ports",
      plan_free_get: "Konto erstellen",
      plan_premium_get: "Premium holen",
      plan_bungee_get: "Paket holen",
      plan_custom_get: "Benutzerdefiniert holen",
      plan_free_support: "Guter Support",
      plan_premium_support: "Dedizierter Support",
      plan_bungee_support: "Priorisierter Support",
      features_title: "Warum ist es so toll?",
      features_subtitle: "Weil wir darauf bestimmt sind, dir das Beste anzubieten.",
      features_support_title: "Live Support",  
      features_support_subtitle: 'Unser Support-Team ist immer auf unserem <a href="%s" class="text-white text-underline" target="_blank">Discord-Server</a> da, um dir zu helfen!',
      features_uptime_title: "99% Verfügbarkeit",
      features_uptime_subtitle: 'Wir sagen das nicht nur, schaue <a href="%s" class="text-white text-underline" target="_blank">hier</a> selber nach.',
      features_tech_title: "Spitzentechnologie", 
      features_tech_subtitle: "Wir verbessern laufend unsere Dienste, sodass dein Server immer auf dem neuesten Stand ist.",
      features_title2: "Bei allen Tarifen inklusive", 
      features_subtitle2: "Das sind die Funktionen und Eigenschaften von allen Minecraft-Hostinig Tarifen, die wir anbieten.",
      features_ddos_title: "DDoS-Schutz", 
      features_ddos_subtitle: "Wir benuzten ein Layer-7 Proxy-System, um jegliche distributed denial of service Attacken einfach zu umgehen..",
      features_disk_title: "NVMe SSD", 
      features_disk_subtitle: "Die Startzeit deines Servers hängt voll und ganz von der Festplatte ab. Deshalb benutzen wir nur das Beste.",
      features_scalability_title: "Skalierbarkeit", 
      features_scalability_subtitle: "Unser Kontrollzentrum ermöglicht es, deinen Server innerhalb wenigen Klicks zu verbessern. Starte mit dem was du brauchst und verbessere deinen Server bei entsprechendem Wachstum.",
      features_panel_title: "Pterodactyl Kontrollzentrum", 
      features_panel_subtitle: "Das verwalten mehrer Server war noch nie einfacher, als wie mit Pterodactyl. Greife direkt auf deine Dateien zu, verwende das Serverterminal und verwalte Unterbenutzer.",
      features_sftp_title: "SFTP", 
      features_sftp_description: "Wir lassen Sicherheit nie im Stich. Das Secure File Transfer Protocol, welches wir verwenden, ermöglicht es deine Dateien von überall sicher verwalten.",
      features_scheduler_title: "Task-Scheduler", 
      features_scheduler_subtitle: "Wir verwenden CRON, um es dir zu erlauben bestimmte Aktivitäten wie Neustarts und andere Befehle automatisch auszuführen.",
      about_title: "Über Uns", 
      about_subtitle: "Es ist unser Ziel, dir das Beste und qualitativstes Hosting anzubieten. Wir arbeiten Tag und Nacht dafür, die besten Nodes einzurichten, sodass du Lag-freies und angenehmes Gameplay mit deinen Freunden auf deinem Minecraft-Server genießen kannst.",
      reviews_title: "Bewertungen",
      reviews_subtitle: "Nimm nicht unser Wort für was wir sagen. Das sagen unsere Kunden!",
      review1_title: "MChost ist das beste Hosting.", 
      review1_text: "MChost ist der beste Host den ich verwendet habe. Die Leistung ist super, selbst wenn der Server nicht mit viel RAM läuft.", 
      review2_title: "MChost ist sehr gut.",
      review2_text: "MChost ist sehr gut. Kein Lag, kein TPS unter 19.9. Es ist toll!", 
      review3_title: "Bester Hostinganbieter", 
      review3_text: "MChost ist einer der besten Hostinganbieter, die ich je verwendet habe und ich bin froh MChost gefunden zu haben. Hat mir etwas Geld gespart!",
      review4_title: "Ausgezeichnet", 
      review4_text: "Man bekommt SFTP und ein Kontrollzentrum. Es ist nicht wie andere Anbieter, die limitieren was man machen kann. Es ist als hätte man dafür bezahlt. Ich bin sehr glücklich darüber, MChost gefunden zu haben.",
      panel_title: "Wir stelen vor: Pterodactyl", 
      panel_subtitle: "Pterodactyl ist das beste Kontrollzentrum für Minecraft-Server, sicher entwickelt, alle Server laufen in isolierten Docker-Container, während eine schöne und intuitive BO präsentiert wird.",
      need_support: 'Suchst du nach weiteren Informationen? <a href="%s">Kontaktiere den Support hier</a> oder trete unserer <a href="%s" target="_blank">Discord-Community</a> bei.',
      start_title: "Starte noch heute deinen Server!",
      start_subtitle: "Auf was wartest du? Es kostet nichts!",
      support_title: "Live Experten-Support",
      support_subtitle: 'Brauchst du sofortige Unterstützung oder hast du mehrere Fragen? Trete unserer <a href="https://discord.gg/Wx95Nx3" target="_blank">Discord-Community</a> bei und rede mit einem Support-Agenten. Du kannst uns auch eine Email bei <a href="mailto:support@mchost.cc">support@mchost.cc</a> zukommen lassen.',
      footer_information: "Information",
      footer_pages: "Seiten",
      footer_more: "Mehr",
      footer_page_terms: "Allgemeine Geschäftsbedingungen",
      footer_page_privacy: "Datenschutzerkärung",
      footer_page_mc: "Minecraft-Hosting",
      footer_page_pricing: "Preise",
      footer_page_order: "Bestellen",
      footer_page_blog: "Blog",
      footer_powered: "Unterstüzt von",
      footer_copyright: "Alle Rechte Vorbehalten."
    },
    contact: {
      title: "Kontaktiere Uns",
      field_name: "Name",
      placeholder_name: "Bitte gebe deinen Namen ein",
      field_organisation: "Organisation",
      placeholder_organisation: "Bitte gebe den Namen deiner Organisation ein",
      field_email: "Email",
      placeholder_email: "Bitte gebe deine Email ein",
      field_phone: "Telefon",
      placeholder_phone: "Bitte gebe deine Telefonnummer ein",
      field_message: "Nachricht",
      placeholder_message: "Deine Nachricht für uns",
      button_send: "Absenden",
      note: '* Diese Felder werden benötigt. Indem du "Absenden" drückst, stimmst du den <a href="%s" target="_blank">Allgemeinen Geschäftsbedingungen</a> zu.'
    },
    hosting: {
      title: "Minecraft-Hosting",
      subtitle: "Kostenloses Hosting mit 2GB RAM. 100% NVMe SSD Speicher, verfügbar 24/7, keine Warteschlagen, kein Spieler-Limit, kein Plugin-Limit, funktioniert mit jeder beliebigen Minecraft Server-Software! Starte jetzt kostenlos!",
      plan_traffic: "Unendliche Bandbreite",
      plan_ddos: "Layer-7 DDoS-Schutz"
    },
    order: {
      title: "Bestellung",
      field_name: "Name",
      placeholder_name: "Bitte gebe deinen Namen ein",
      field_email: "Email",
      placeholder_email: "Bitte gebe deine Email ein",
      field_pp_email: "PayPal E-mail",
      field_more: "Zusätzliche Anweisungen",
      button: "Bestellung anfordern",
      note: '* Diese Felder sind benötigt. Indem du "Absenden" drückst, stimmst du den <a href="%s" target="_blank">Allgemeinen Geschäftsbedingungen</a> zu.'
    },
    support: {
      title: "Support",
      subtitle: "Du kannst uns jederzeit erreichen. Hier sind verschiedene Optionen.",
      faq_title: "Häufig gesellte Fragen",
      faq_text: "Schaue in unserer Wissensdatenbank vorbei. Es kann sein, dass dort deine Frage bereits beantwortet wurde.",
      dc_title: "Discord Live Support",
      dc_text: "Klicke auf den Knopf, um unserem Discord-Server beizutreten.",
      email_title: "E-mail",
      email_text: 'Sende eine Email an <a href="mailto:support@mchost.cc">support@mchost.cc</a> und wir werden dir innerhalb von 12 Stunden antworten.',
      form_title: "Kontaktformular",
      form_text: "Oder sende uns einfach eine Nachricht durch das Kontaktformular."
    },
    arc_earn: {
      title: "Credits verdienen",
      subtitle: "Du kannst Credits verdienen, welche für weitere Resourcen verwendet werden können, indem du diese Seite offen lässt. Du bekommst jede Stunde einen Credit.", 
      label: "BITTE GEBE EINS DER FOLGENDEN EIN",
      placeholder: "Discord-ID, Kunden-ID oder Benutzernamen.",
      get_dc: "Hole deine Discord-ID",
      get_panel: "Hole deinen Benutzernamen",
      get_cid: "Hole deine Kunden-ID",
      unsure: 'Bist du nicht sicher, wie du die Informationen holst? <a href="$s" target="_blank">Kontaktiere uns.',
      keep_open: "Lasse diese Seite auf, um Credits zu verdienen.",
      earned: 'Während dieser Sitzung verdient: <b class="credits">0</b> Credits',
      btn_quit: "Beenden",
      btn_refresh: "Neuladen",
      btn_blank: "Leer", 
      text: 'Lasse diese Seite offen und du bekommst jede Stunde ein Credit. Falls du diese Seite schließt, hast du 5 Minuten Zeit die Seite wiederzuöffnen bevor deine Sitzung zurückgesetzt wird. Falls du mehr Credits pro Stunde erhalten willst, <a href="%s" target="_blank">folge diesem Tutorial.</a>.',
      video_subtitle: "Du kannst Credits erhalten, die für zusätzliche Resourcen verwendet werden können, indem du eine Werbung anschaust.", 
      short_title: "Erhalte einen Credit umsonst!",
      short_new: 'Öffne diese URL <a href="%s">%s</a>, um eine Belohnung zu erhalten.',
      short_success: "Du hast deine Belohnung erfolgreich erhalten!",
      short_error_title: "Fehler!",
      short_error_text: "Die Belohnung wurde bereits eingelöst oder existiert nicht.",
      short_error_new: 'Eine nicht eingelöste URL für dich: <a href="%s">%s</a>'
    },
    gdpr: {
      text: "Unsere Website benutzt Cookies. Schaue unsere Datenschutzerklärung für mehr Informationen an.",
      accept: "Annehmen",
      privacy: "Datenschutzerklärung"
    },
    dashboard: {
      welcome: "Willkommen zu deinem Kundenbereich!",
      btn_panel: "Kontrollzentrum",
      btn_logout: "Abmelden",
      servers: "Server",
      server_create: "Server erstellen",
      server_name: "Name",
      server_actions: "Aktionen",
      server_unlimited: "Unendlich",
      balance: "MChost-Guthaben",
      balance_text: "Credits verfügbar",
      balance_add: "Hinzufügen",
      balance_store: "Store",
      balance_send: "Senden",
      create_title: "Server erstellen",
      create_name: "Server-Namen",
      create_quota: "Deine übrige RAM Quote ist %s MB",
      create_location: "Standort",
      create_type: "Serverart",
      create_btn: "Erstellen!",
      btn_close: "Schließen",
      panel_title: "Im Kontrollzentrum anmelden",
      panel_subtitle: "Das sind die Daten, welche du benutzen kannst, um dich im Kontrollzentrum anzumelden. Falls du diese änderst, werden die hier nicht aktualisiert.",
      panel_username: "Benutzername", 
      panel_pass: "Passwort",
      panel_show_pass: "Passwort anzeigen",
      btn_login: "Anmelden",
      panel_open: "Kontrollzentrum öffnen",
      add_title: "Credits erhalten",
      add_buy: "Credits",
      add_buy_sub: "Kaufe mehr Credits mit deiner Bankarte oder PayPal.",
      credits: "Credits",
      add_buy_buy: "Weiter",
      add_giftcard: "Gutschein einlösen",
      add_giftcard_sub: "Löse einen MChost Gutschein ein, um mehr Credits zu erhalten. ",
      gift_card: "Gutschein",
      add_giftcard_btn: "Einlösen",
      add_idle: "Idling",
      add_idle_sub: "Du kannst kostenlose Credits verdienen, indem du deinen Browser offen lässt.",
      add_idle_btn: "Idling beginnen",
      add_app: "Schaue eine Werbung an <small>(Android)</small>",
      add_app_sub: "Erhalte kostenlose Credits, indem du eine Werbung auf unserer Android-App anschaust.",
      add_app_btn: "Herunterladen",
      add_vid: "Werbung anschauen <small>(Desktop)</small>",
      add_vid_sub: "Du kannst auch auf deinem PC Werbungen anschauen, um Credits zu verdienen.",
      add_vid_btn: "Anschauen",
      add_short: "Verkürzte URLs",
      add_short_sub: "Klicke auf den Knopf, um kostenlose Credits zu erhalten",
      add_short_btn: "Los",
    }
  }
}
